### ISSUE TITLE
Incremental classes in clients 

### ISSUE THREAD

**Issue by rishabhpahuja** [conditionWang/FCIL#1]
I was wondering that in the paper when you mention that you add the same number of classes in the clients to perform incremental in classes, the new classes added in the same client, are they of the same category? For e.g. suppose I have a model that predicts dog breeds. Suppose client 1 receives data on breed x  and incremental learning is performed with this new data for breed and client 2 received data on breed y, and similarly incremental learning is performed for breed y, so are breed x= breed y or can they even be different breeds?

**Comment by conditionWang** [comment]
Actually, the annotation principle is controlled by the FL framework administrator instead of individual clients, which means if samples are annotated with different labels, they are different for all clients. For your question, the breed x of client 1 and the breed y of client 2 are definitely two different classes.

**Comment by rishabhpahuja** [comment]
But then how will the global model be merged then? For example if the server sends different labels to clients, for e.g. if the model was initially trained on 5 labels and if the server sends 1 label to client 1 and a different label to client 2, so now while updating the global model, how will FedAvg be useful? Because now the global model should be able to predict 7 classes but FedAvg is just going to take the aggregation of two models which predict different 6 classes.

**Comment by conditionWang** [comment]
We assume the FL administrator updates the annotation rule at every round, in this case, the administrator directly decides the total number of classes at every round. Therefore, all local models are set to the same architecture with the same number of classes. Considering your case, the two models of clients 1 and 2 share the same architecture and both of them are fixing the 7-class classification problem, though different clients own part of classes.

**Comment by rishabhpahuja** [comment]
Okay got it!
Thank you

Just one more question, in fl_main.py, line 85 and 93, you guys have used the same condition.Is that a typo or was it done intentionally?

**Comment by conditionWang** [comment]
line 85 is preparing for the client setting, while line 93 is the model structure setting, which share the same condition in incremental learning.
