### ISSUE TITLE
tiny_imagenet

### ISSUE THREAD

**Issue by wufeng10010** [conditionWang/FCIL#3]
May I ask if your processing of the tinyimagenet dataset is to separate 50 samples from each class in its training,and then use them as  test set, which is the testing effect of tinyimagenet in your paper

**Comment by conditionWang** [comment]
That's right.

**Comment by wufeng10010** [comment]
thank you! Also, I'd like to ask what dataset is ImageNet-Subset, which is the Mini-ImageNet dataset?
