### ISSUE TITLE
GPU requirement for tiny-imagenet-200 training

### ISSUE THREAD

**Issue by Ananya21162** [conditionWang/FCIL#4]
Hey, I am also researching in the federated class incremental learning domain and found your paper to be very interesting. I tried running the code on A-100 80 GB machine but it throws CUDA out of memory error even with a batch size of 32 instead of 128. Can you tell me about the gpu requirements for training on tiny-imagenet-200?

**Comment by Ananya21162** [comment]
Hey, I am also researching in the federated class incremental learning domain and found your paper to be very interesting. I tried running the code on A-100 80 GB machine but it throws CUDA out of memory error even with a batch size of 32 instead of 128. Can you tell me about the gpu requirements for training on tiny-imagenet-200?

**Comment by conditionWang** [comment]
You can try reshaping the image to a smaller size and try data-parallel across multiple GPUs.
